# Lab | SQL Select

In [3]:
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="/Users/unoma/IRONHACK/ironhack_service_account_big_query.json"

from google.cloud import bigquery
# Instantiates a client for BigQuery Service
client = bigquery.Client()

import six
six.moves.reload_module(six)

## Challenge 1 - Who have published what at where

Write a SELECT query that joins various tables to figure out what titles each author has published at which publishers.

In [12]:
query= ('''SELECT a.au_id AS AUTHOR_ID, a.au_lname AS LAST_NAME, a.au_fname as FINAL_NAME, t.title AS TITLE, p.pub_name AS PUBLISHER
FROM publications.authors as a
LEFT JOIN publications.titleauthor as ta ON a.au_id = ta.au_id
LEFT JOIN publications.titles as t ON t.title_id = ta.title_id
LEFT JOIN publications.publishers as p ON p.pub_id = t.pub_id
ORDER BY AUTHOR_ID''')

In [13]:
query_job = client.query(query=query)
query_job.to_dataframe()

,AUTHOR_ID,LAST_NAME,FINAL_NAME,TITLE,PUBLISHER
0,172-32-1176,White,Johnson,Prolonged Data Deprivation: Four Case Studies,New Moon Books
1,213-46-8915,Green,Marjorie,The Busy Executive's Database Guide,Algodata Infosystems
2,213-46-8915,Green,Marjorie,You Can Combat Computer Stress!,New Moon Books
3,238-95-7766,Carson,Cheryl,But Is It User Friendly?,Algodata Infosystems
4,267-41-2394,O'Leary,Michael,Cooking with Computers: Surreptitious Balance ...,Algodata Infosystems
5,267-41-2394,O'Leary,Michael,"Sushi, Anyone?",Binnet & Hardley
6,274-80-9391,Straight,Dean,Straight Talk About Computers,Algodata Infosystems
7,341-22-1782,Smith,Meander,None,None
8,409-56-7008,Bennet,Abraham,The Busy Executive's Database Guide,Algodata Infosystems
9,427-17-2319,Dull,Ann,Secrets of Silicon Valley,Algodata Infosystems
10,472-27-2349,Gringlesby,Burt,"Sushi, Anyone?",Binnet & Hardley
11,486-29-1786,Locksley,Charlene,Emotional Security: A New Algorithm,New Moon Books
12,486-29-1786,Locksley,Charlene,Net Etiquette,Algodata Infosystems
13,527-72-3246,Greene,Morningstar,None,None
14,648-92-1872,Blotchet-Halls,Reginald,Fifty Years in Buckingham Palace Kitchens,Binnet & Hardley
15,672-71-3249,Yokomoto,Akiko,"Sushi, Anyone?",Binnet & Hardley
16,712-45-1867,del Castillo,Innes,Silicon Valley Gastronomic Treats,Binnet & Hardley
17,722-51-5454,DeFrance,Michel,The Gourmet Microwave,Binnet & Hardley
18,724-08-9931,Stringer,Dirk,None,None
19,724-80-9391,MacFeather,Stearns,Computer Phobic AND Non-Phobic Individuals: Be...,Binnet & Hardley
20,724-80-9391,MacFeather,Stearns,Cooking with Computers: Surreptitious Balance ...,Algodata Infosystems
21,756-30-7391,Karsen,Livia,Computer Phobic AND Non-Phobic Individuals: Be...,Binnet & Hardley
22,807-91-6654,Panteley,Sylvia,"Onions, Leeks, and Garlic: Cooking Secrets of ...",Binnet & Hardley
23,846-92-7186,Hunter,Sheryl,Secrets of Silicon Valley,Algodata Infosystems
24,893-72-1158,McBadden,Heather,None,None
25,899-46-2035,Ringer,Anne,Is Anger the Enemy?,New Moon Books
26,899-46-2035,Ringer,Anne,The Gourmet Microwave,Binnet & Hardley
27,998-72-3567,Ringer,Albert,Is Anger the Enemy?,New Moon Books
28,998-72-3567,Ringer,Albert,Life Without Fear,New Moon Books

## Challenge 2 - Who Have Published How Many At Where?

Query how many titles each author has published at each publisher.

In [ ]:
query= ('''SELECT a.au_id AS AUTHOR_ID, a.au_lname AS LAST_NAME, a.au_fname as FINAL_NAME, t.title AS TITLE, p.pub_name AS PUBLISHER
FROM publications.authors as a
LEFT JOIN publications.titleauthor as ta ON a.au_id = ta.au_id
LEFT JOIN publications.titles as t ON t.title_id = ta.title_id
LEFT JOIN publications.publishers as p ON p.pub_id = t.pub_id
ORDER BY AUTHOR_ID''')